### ISSUE TITLE
Latest version isn't on ForgeBox

### ISSUE THREAD

**Issue by mjclemente** [coldfumonkeh/oauth2#12]
1) This is an awesome repo, and was very helpful getting me started with oauth2

2) Looks like it's been restructured with providers added. Care to bump it on ForgeBox? I installed it via CommandBox and got a bit confused why it wasn't the same as I was seeing here.

Thanks again for the project!

**Comment by coldfumonkeh** [comment]
Hey @mjclemente! Thank you for pointing this out, and I'm sorry it caused confusion. I've updated to v2.0.0 and have pushed the latest to ForgeBox.

**Comment by mjclemente** [comment]
Many thanks! Really appreciate it.
