### ISSUE TITLE
get an OAuth token in exchange private key (no user involvement)

### ISSUE THREAD

**Issue by happysailingdude** [coldfumonkeh/oauth2#6]
Hi - may I please ask if your library will help me with the following use case:

I'm following Google's instructions here https://developers.google.com/search/apis/indexing-api/v3/prereqs (please scroll down to "Get an access token")

I've got to this part:

![image](https://user-images.githubusercontent.com/5772853/57481722-a4fbb480-729a-11e9-8f03-7c5f665a82f1.png)

I am trying to get an OAuth token in exchange the private key that I have - can your library help me with that? This will be my server contacting Google's (no user involved and no redirecting I don't believe).

Thank you very much in advance.

**Comment by coldfumonkeh** [comment]
Hey @happysailingdude 

Take a look at the Google test spec which shows the various auth methods in use: https://github.com/coldfumonkeh/oauth2/blob/master/tests/specs/googleTest.cfc

Essentially you need to build up the redirect link first of all:

```

**Comment by coldfumonkeh** [comment]
Hey @happysailingdude 

Take a look at the Google test spec which shows the various auth methods in use: https://github.com/coldfumonkeh/oauth2/blob/master/tests/specs/googleTest.cfc

Essentially you need to build up the redirect link first of all:

```
var strState = createUUID();
var aScope = [
    'https://www.googleapis.com/auth/drive.readonly',
    'https://www.googleapis.com/auth/analytics.readonly'
];
var strURL = oGoogle.buildRedirectToAuthURL(
    scope = aScope,
    state = strState
);
```

You then need to run a `cflocation` redirect to the value returned in the `strURL` variable which will transfer the OAuth2 process over to Google.
This will return a `code` value in the URL to your redirect URI value.

On this page, wherever you have it, you need to then have the following code block to obtain the access token:

```
oGoogle.makeAccessTokenRequest(
    code = URL.code
);
```

**Comment by coldfumonkeh** [comment]
Closing this down as the Google Index component now handles this
