### ISSUE TITLE
Issues when Scopes returning an bytecode array and success message

### ISSUE THREAD

**Issue by JattJames** [coldfumonkeh/oauth2#7]
Hi, I am using the Github CFC for connecting it and getting it to work, when i pass the scopes like: user, public_repo to the method, as an array and a string value, it is authenticating it but returning only the success true and the java byte code 

is this something which is missing here 

![image](https://user-images.githubusercontent.com/6989660/60816736-b533f100-a170-11e9-8ce8-d7be3c303e5c.png)

**Comment by coldfumonkeh** [comment]
@gavyjatt Have you tried decrypting / converting the binary encoded `content` data to see what it actually returns?

**Comment by gavyjatt** [comment]
when i decrypted it, it gave me this url 

access_token=lsdh4756khgedrkth39459347kjghedgdkfjgh&scope=&token_type=bearer

**Comment by gavyjatt** [comment]
what to do after i had this decrypted value with me, docs does not explain anything

**Comment by gavyjatt** [comment]
will you mind putting some docs on after the one response i got how to move fwd with actually doing some things after toke, like getting username,email etc etc

**Comment by coldfumonkeh** [comment]
@gavyjatt This CFC only deals with fetching access tokens for the APIs. You will need to visit the actual documentation pages for the API you are using to then see how you can use the access token.

**Comment by coldfumonkeh** [comment]
https://developer.github.com/v3/
